ThreeDotsMenu = "//header/div[1]/div[2]/lgx-user-menu[1]/div[1]/a[1]/*[1]"
SignUpButton = "//a[contains(text(),'Sign up')]"
FirstNameInput = "xpath://body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[3]/div[1]/div[2]/form[1]/div[1]/input[1]"
LastNameInput = "xpath://body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[3]/div[1]/div[2]/form[1]/div[2]/input[1]"
EmailInput = "xpath://body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[3]/div[1]/div[2]/form[1]/div[3]/input[1]"
PasswordInput = "xpath//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[3]/div[1]/div[2]/form[1]/div[4]/input[1]"
SignUpButtonClick = "xpath://body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[3]/div[1]/input[1]"
LoginButton = "xpath:(//input[@id='login-button'])[1]"
Username = "id:user-name"
Password = "id:password"
